/** Tech: produto, engenharia, startups, gadgets, segurança, open source e ciência — sem política BR e sem laboratórios de IA. */
export const TECH_PROFILES = [
  { handle: "Apple", name: "Apple", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Apple. iPhone, Mac, Vision e os serviços da empresa." },
  { handle: "Google", name: "Google", group: "tech-empresas", section: "tech", blurb: "Conta oficial do Google. Android, busca, Pixel e a plataforma." },
  { handle: "Microsoft", name: "Microsoft", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Microsoft. Windows, Azure, Office e GitHub." },
  { handle: "nvidia", name: "NVIDIA", group: "tech-empresas", section: "tech", blurb: "Conta oficial da NVIDIA. GPUs, PCs e a infraestrutura que roda o restante da indústria." },
  { handle: "Meta", name: "Meta", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Meta. Facebook, Instagram, WhatsApp e Reality Labs." },
  { handle: "amazon", name: "Amazon", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Amazon. Varejo, AWS e dispositivos Echo e Kindle." },
  { handle: "Tesla", name: "Tesla", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Tesla. Carros, energia e robótica de consumo." },
  { handle: "intel", name: "Intel", group: "tech-empresas", section: "tech", blurb: "Conta oficial da Intel. Processadores, PCs e fabricação de chips." },
  { handle: "AMD", name: "AMD", group: "tech-empresas", section: "tech", blurb: "Conta oficial da AMD. CPUs, GPUs e o hardware que compete com a Intel e a NVIDIA." },

  { handle: "verge", name: "The Verge", group: "tech-imprensa", section: "tech", blurb: "Site de tecnologia e cultura digital. Gadgets, software e as empresas que os fazem." },
  { handle: "TechCrunch", name: "TechCrunch", group: "tech-imprensa", section: "tech", blurb: "Notícias de startups e venture capital. Referência do Vale do Silício." },
  { handle: "wired", name: "WIRED", group: "tech-imprensa", section: "tech", blurb: "Revista de tecnologia, ciência e cultura. Reportagens longas sobre o que vem depois." },
  { handle: "arstechnica", name: "Ars Technica", group: "tech-imprensa", section: "tech", blurb: "Jornalismo técnico: ciência, hardware, política de internet e segurança." },
  { handle: "theinformation", name: "The Information", group: "tech-imprensa", section: "tech", blurb: "Reportagem investigativa sobre big techs e o mercado de tecnologia." },
  { handle: "BloombergTech", name: "Bloomberg Tech", group: "tech-imprensa", section: "tech", blurb: "Cobertura de tecnologia da Bloomberg. Mercados, empresas e política setorial." },
  { handle: "CNET", name: "CNET", group: "tech-imprensa", section: "tech", blurb: "Reviews e noticiário de consumo. Celulares, notebooks e o que chega às lojas." },
  { handle: "engadget", name: "Engadget", group: "tech-imprensa", section: "tech", blurb: "Site clássico de gadgets. Lançamentos, hands-on e cultura de produto." },
  { handle: "theregister", name: "The Register", group: "tech-imprensa", section: "tech", blurb: "Jornalismo britânico de TI. Enterprise, chips e o lado seco da indústria." },
  { handle: "9to5mac", name: "9to5Mac", group: "tech-imprensa", section: "tech", blurb: "Cobertura diária do ecossistema Apple. Rumores, reviews e software." },

  { handle: "ycombinator", name: "Y Combinator", group: "tech-startups", section: "tech", blurb: "Aceleradora de startups. Demo Day, ensaios e o canônico do ecossistema." },
  { handle: "a16z", name: "a16z", group: "tech-startups", section: "tech", blurb: "Andreessen Horowitz. Fundo que marca a conversa de venture e produto." },
  { handle: "paulg", name: "Paul Graham", group: "tech-startups", section: "tech", blurb: "Cofundador do Y Combinator. Ensaios sobre founders, startups e como começar." },
  { handle: "garrytan", name: "Garry Tan", group: "tech-startups", section: "tech", blurb: "CEO do Y Combinator. Fala do batch, de San Francisco e de construir empresa." },
  { handle: "pmarca", name: "Marc Andreessen", group: "tech-startups", section: "tech", blurb: "Cofundador da a16z. Software, mercados e o manifesto de construir." },
  { handle: "naval", name: "Naval", group: "tech-startups", section: "tech", blurb: "Naval Ravikant. Angel, AngelList e aforismos de alavancagem e equity." },
  { handle: "sequoia", name: "Sequoia", group: "tech-startups", section: "tech", blurb: "Sequoia Capital. Fundo histórico de empresas de tecnologia." },
  { handle: "patrickc", name: "Patrick Collison", group: "tech-startups", section: "tech", blurb: "CEO da Stripe. Infraestrutura de pagamentos e o ofício de escalar produto." },

  { handle: "MKBHD", name: "Marques Brownlee", group: "tech-gadgets", section: "tech", blurb: "YouTuber de reviews de gadgets. Uma das vozes mais vistas de hardware no mundo." },
  { handle: "ijustine", name: "iJustine", group: "tech-gadgets", section: "tech", blurb: "Justine Ezarik. Reviews de iPhone, gadgets e o dia a dia de hardware." },
  { handle: "LinusTech", name: "Linus Tech Tips", group: "tech-gadgets", section: "tech", blurb: "Canal de PCs e periféricos. Benchmarks, montagens e o laboratório da LTT." },
  { handle: "UnboxTherapy", name: "Unbox Therapy", group: "tech-gadgets", section: "tech", blurb: "Lewis Hilsenteger. Unboxings e o primeiro contato com o gadget novo." },
  { handle: "AustinEvans", name: "Austin Evans", group: "tech-gadgets", section: "tech", blurb: "Reviews de TVs, consoles e PCs. Hardware de sala e de mesa." },
  { handle: "dave2d", name: "Dave2D", group: "tech-gadgets", section: "tech", blurb: "Dave Lee. Notebooks, handhelds e o recorte fino de portáteis." },
  { handle: "Mrwhosetheboss", name: "Mrwhosetheboss", group: "tech-gadgets", section: "tech", blurb: "Arun Maini. Comparativos de celulares e o que vale comprar." },
  { handle: "ZackNelson", name: "JerryRigEverything", group: "tech-gadgets", section: "tech", blurb: "Zack Nelson. Testes de durabilidade — o que o telefone aguenta de verdade." },

  { handle: "briankrebs", name: "Brian Krebs", group: "tech-seguranca", section: "tech", blurb: "Jornalista de KrebsOnSecurity. Crime digital, vazamentos e a indústria do scam." },
  { handle: "troyhunt", name: "Troy Hunt", group: "tech-seguranca", section: "tech", blurb: "Criador do Have I Been Pwned. Breaches, senhas e educação de segurança web." },
  { handle: "KimZetter", name: "Kim Zetter", group: "tech-seguranca", section: "tech", blurb: "Repórter de cibersegurança. Stuxnet, infra crítica e a newsletter Zero Day." },
  { handle: "schneierblog", name: "Bruce Schneier", group: "tech-seguranca", section: "tech", blurb: "Criptógrafo e ensaísta. Segurança como sistema, não como produto." },
  { handle: "SwiftOnSecurity", name: "SwiftOnSecurity", group: "tech-seguranca", section: "tech", blurb: "Conta de operação e cultura de segurança. Windows, identidade e o dia a dia do SOC." },
  { handle: "CISAgov", name: "CISA", group: "tech-seguranca", section: "tech", blurb: "Agência de cibersegurança dos EUA. Alertas, KEV e orientação a operadores." },
  { handle: "haveibeenpwned", name: "Have I Been Pwned", group: "tech-seguranca", section: "tech", blurb: "Conta do serviço de consulta a vazamentos. Avisos quando uma base nova entra." },
  { handle: "DarkReading", name: "Dark Reading", group: "tech-seguranca", section: "tech", blurb: "Redação de segurança da informação. Vulnerabilidades, ransomware e política." },

  { handle: "github", name: "GitHub", group: "tech-devs", section: "tech", blurb: "Conta oficial do GitHub. Repositórios, Actions e a praça do código aberto." },
  { handle: "vercel", name: "Vercel", group: "tech-devs", section: "tech", blurb: "Conta oficial da Vercel. Next.js, deploy e a plataforma de frontend." },
  { handle: "GergelyOrosz", name: "Gergely Orosz", group: "tech-devs", section: "tech", blurb: "The Pragmatic Engineer. Carreira, times e o ofício de engenharia em produto." },
  { handle: "ThePrimeagen", name: "ThePrimeagen", group: "tech-devs", section: "tech", blurb: "Engenheiro e streamer. Vim, performance e a cultura de quem escreve código." },
  { handle: "b0rk", name: "Julia Evans", group: "tech-devs", section: "tech", blurb: "Wizard Zines. Explica redes, debugging e sistemas com clareza rara." },
  { handle: "charity", name: "Charity Majors", group: "tech-devs", section: "tech", blurb: "Honeycomb. Observabilidade, on-call e o que significa operar software." },
  { handle: "addyosmani", name: "Addy Osmani", group: "tech-devs", section: "tech", blurb: "Chrome e performance web. Frontend, Core Web Vitals e engenharia de produto." },
  { handle: "Rich_Harris", name: "Rich Harris", group: "tech-devs", section: "tech", blurb: "Criador do Svelte. Compiladores, DX e o futuro das UIs na web." },
];
