/** Seed de IA — não esvaziar; labels Empresas/CEOs/Cientistas/Imprensa/Devs. */
export const AI_PROFILES = [
  { handle: "grok", name: "Grok", group: "labs", section: "ai", blurb: "Assistente de IA da xAI, empresa fundada por Elon Musk. Conta oficial do produto." },
  { handle: "OpenAI", name: "OpenAI", group: "labs", section: "ai", blurb: "Laboratório que cria o ChatGPT, o GPT e o Sora. Uma das empresas centrais da IA generativa." },
  { handle: "AnthropicAI", name: "Anthropic", group: "labs", section: "ai", blurb: "Laboratório por trás do Claude. Foco em IA constitucional e segurança de modelos." },
  { handle: "GoogleDeepMind", name: "Google DeepMind", group: "labs", section: "ai", blurb: "Braço de pesquisa de IA do Google. Gemini, AlphaGo e AlphaFold saíram daqui." },
  { handle: "claudeai", name: "Claude", group: "labs", section: "ai", blurb: "Conta do assistente Claude, da Anthropic. Anúncios de produto e do app." },
  { handle: "MistralAI", name: "Mistral", group: "labs", section: "ai", blurb: "Laboratório francês de modelos abertos e comerciais. Rival europeu das big techs de IA." },
  { handle: "perplexity_ai", name: "Perplexity", group: "labs", section: "ai", blurb: "Busca conversacional com fontes. Alternativa ao Google para pesquisar com IA." },
  { handle: "AIatMeta", name: "Meta AI", group: "labs", section: "ai", blurb: "Pesquisa e produtos de IA da Meta. Família Llama e ferramentas abertas." },
  { handle: "huggingface", name: "Hugging Face", group: "labs", section: "ai", blurb: "Plataforma onde a comunidade publica modelos, datasets e demos de IA." },
  { handle: "cursor_ai", name: "Cursor", group: "labs", section: "ai", blurb: "Editor de código com IA. Muito usado por quem programa com agentes." },
  { handle: "sama", name: "Sam Altman", group: "lideres", section: "ai", blurb: "CEO da OpenAI. Voz principal da empresa sobre ChatGPT, modelos e política de IA." },
  { handle: "demishassabis", name: "Demis Hassabis", group: "lideres", section: "ai", blurb: "CEO da Google DeepMind. Cientista por trás do AlphaGo e do AlphaFold." },
  { handle: "DarioAmodei", name: "Dario Amodei", group: "lideres", section: "ai", blurb: "CEO e cofundador da Anthropic. Pesquisa escala de modelos e riscos da IA." },
  { handle: "gdb", name: "Greg Brockman", group: "lideres", section: "ai", blurb: "Presidente e cofundador da OpenAI. Fala de pesquisa, produto e engenharia." },
  { handle: "arthurmensch", name: "Arthur Mensch", group: "lideres", section: "ai", blurb: "CEO e cofundador da Mistral AI. Representa a aposta europeia em modelos próprios." },
  { handle: "AravSrinivas", name: "Aravind Srinivas", group: "lideres", section: "ai", blurb: "CEO e cofundador da Perplexity. Defende busca com respostas citadas." },
  { handle: "ylecun", name: "Yann LeCun", group: "pesquisa", section: "ai", blurb: "Cientista-chefe de IA da Meta. Pioneiro de redes neurais e crítico do alarmismo existencial." },
  { handle: "karpathy", name: "Andrej Karpathy", group: "pesquisa", section: "ai", blurb: "Pesquisador e professor. Ex-diretor de IA da Tesla e um dos primeiros da OpenAI." },
  { handle: "ilyasut", name: "Ilya Sutskever", group: "pesquisa", section: "ai", blurb: "Cofundador da OpenAI e da SSI. Figura-chave no treino dos primeiros GPT." },
  { handle: "elonmusk", name: "Elon Musk", group: "lideres", section: "ai", blurb: "CEO da Tesla, SpaceX e xAI. Comenta modelos, robótica, energia e política de IA." },
  { handle: "JensenHuang", name: "Jensen Huang", group: "lideres", section: "ai", blurb: "CEO da NVIDIA. Quase toda a infraestrutura de treino de IA roda nos chips da empresa." },
  { handle: "satyanadella", name: "Satya Nadella", group: "lideres", section: "ai", blurb: "CEO da Microsoft. Sócia da OpenAI e dona do Copilot em Windows, Office e Azure." },
  { handle: "mustafasuleyman", name: "Mustafa Suleyman", group: "lideres", section: "ai", blurb: "CEO de IA da Microsoft. Cofundou a DeepMind e depois a Inflection." },
  { handle: "AndrewYNg", name: "Andrew Ng", group: "pesquisa", section: "ai", blurb: "Professor de Stanford e fundador da DeepLearning.AI. Um dos maiores educadores de IA." },
  { handle: "drfeifei", name: "Fei-Fei Li", group: "pesquisa", section: "ai", blurb: "Professora de Stanford. Criou o ImageNet, base da visão computacional moderna." },
  { handle: "geoffreyhinton", name: "Geoffrey Hinton", group: "pesquisa", section: "ai", blurb: "Pesquisador pioneiro de deep learning. Prêmio Nobel de Física em 2024; alerta sobre riscos da IA." },
  { handle: "ClementDelangue", name: "Clément Delangue", group: "lideres", section: "ai", blurb: "CEO da Hugging Face. Defende código aberto e a comunidade de modelos." },
  { handle: "DanielaAmodei", name: "Daniela Amodei", group: "lideres", section: "ai", blurb: "Presidenta e cofundadora da Anthropic. Cuida de operação, confiança e crescimento da empresa." },
  { handle: "jackclarkSF", name: "Jack Clark", group: "pesquisa", section: "ai", blurb: "Cofundador da Anthropic. Escreve o Import AI e acompanha política e avaliação de modelos." },
  { handle: "ch402", name: "Chris Olah", group: "pesquisa", section: "ai", blurb: "Pesquisador da Anthropic. Referência em interpretabilidade — entender o que o modelo “pensa”." },
  { handle: "NotTomBrown", name: "Tom Brown", group: "pesquisa", section: "ai", blurb: "Cofundador da Anthropic. Coautor do paper do GPT-3 na OpenAI." },
  { handle: "AmandaAskell", name: "Amanda Askell", group: "pesquisa", section: "ai", blurb: "Pesquisadora da Anthropic. Trabalha alinhamento e o tom/personalidade do Claude." },
  { handle: "TheRundownAI", name: "The Rundown", group: "imprensa", section: "ai", blurb: "Newsletter diária de IA. Resume lançamentos, papers e o que o mercado está discutindo." },
  { handle: "rowancheung", name: "Rowan Cheung", group: "imprensa", section: "ai", blurb: "Fundador do The Rundown. Curadoria rápida do que importa no dia da IA." },
  { handle: "_akhaliq", name: "AK", group: "imprensa", section: "ai", blurb: "Curador de papers e demos. Um dos primeiros a espalhar novidades de pesquisa no X." },
  { handle: "dair_ai", name: "DAIR.AI", group: "imprensa", section: "ai", blurb: "Comunidade educacional de IA. Tutoriais, cursos e resumos de pesquisa para iniciantes e profissionais." },
  { handle: "emollick", name: "Ethan Mollick", group: "imprensa", section: "ai", blurb: "Professor da Wharton. Estuda e ensina como usar IA no trabalho e na educação." },
  { handle: "simonw", name: "Simon Willison", group: "builders", section: "ai", blurb: "Criador do Datasette e do LLM CLI. Documenta na prática o que cada modelo consegue fazer." },
  { handle: "swyx", name: "swyx", group: "builders", section: "ai", blurb: "Engenheiro e escritor (Shawn Wang). Fala de AI Engineer, Latent Space e o ofício de construir com LLMs." },
  { handle: "levelsio", name: "levelsio", group: "builders", section: "ai", blurb: "Maker holandês (Pieter Levels). Constrói produtos solo, muitos com IA, e mostra números reais." },
  { handle: "fchollet", name: "François Chollet", group: "builders", section: "ai", blurb: "Criador do Keras e do teste ARC. Pesquisa inteligência e generalização, além de deep learning." },
  { handle: "hwchase17", name: "Harrison Chase", group: "builders", section: "ai", blurb: "CEO da LangChain. Infraestrutura para agentes e apps em cima de modelos de linguagem." },
  { handle: "bcherny", name: "Boris Cherny", group: "builders", section: "ai", blurb: "Engenheiro da Anthropic. Liderou o Claude Code, o agente de programação da empresa." },
  { handle: "leerob", name: "Lee Robinson", group: "builders", section: "ai", blurb: "VP de Produto para Desenvolvedores na Cursor. Antes foi rosto do Next.js na Vercel." },
  { handle: "mntruell", name: "Michael Truell", group: "builders", section: "ai", blurb: "CEO e cofundador da Anysphere, empresa do Cursor. Fala do editor e de agentes de código." },
  { handle: "OfficialLoganK", name: "Logan Kilpatrick", group: "builders", section: "ai", blurb: "Google DeepMind, produto para desenvolvedores do Gemini. Antes liderou relações com devs na OpenAI." },
  { handle: "theo", name: "Theo", group: "builders", section: "ai", blurb: "Theo Browne. YouTuber e CEO da T3 Chat. Comenta ferramentas de dev e produtos de IA." },
  { handle: "mattpocockuk", name: "Matt Pocock", group: "builders", section: "ai", blurb: "Educador de TypeScript. Ensina tipos, DX e agora fluxos de programação com IA." },
];
