/** Brasil: jornais, política, economia, colunistas e instituições — sem CEOs do Vale. */
export const BRASIL_PROFILES = [
  { handle: "folha", name: "Folha de S.Paulo", group: "br-jornais", section: "brasil", blurb: "Jornal brasileiro. Política, economia e cotidiano do país." },
  { handle: "g1", name: "g1", group: "br-jornais", section: "brasil", blurb: "Portal de notícias da Globo. O recorte mais lido do jornalismo brasileiro." },
  { handle: "Estadao", name: "Estadão", group: "br-jornais", section: "brasil", blurb: "O Estado de S. Paulo. Jornalismo político e econômico." },
  { handle: "UOLNoticias", name: "UOL Notícias", group: "br-jornais", section: "brasil", blurb: "Portal UOL. Noticiário geral, política e cotidiano." },
  { handle: "cnnbrasil", name: "CNN Brasil", group: "br-jornais", section: "brasil", blurb: "Canal de notícias. Política, economia e cobertura ao vivo." },
  { handle: "nexojornal", name: "Nexo", group: "br-jornais", section: "brasil", blurb: "Jornalismo explicativo. Contexto e dados sobre o Brasil." },
  { handle: "revistapiaui", name: "piauí", group: "br-jornais", section: "brasil", blurb: "Revista de reportagem longa. Política, cultura e grandes histórias." },
  { handle: "jornaloglobo", name: "O Globo", group: "br-jornais", section: "brasil", blurb: "Jornal O Globo. Redação do Rio com cobertura nacional." },
  { handle: "BBCBrasil", name: "BBC News Brasil", group: "br-jornais", section: "brasil", blurb: "Serviço brasileiro da BBC. Política e internacional com régua própria." },
  { handle: "metropoles", name: "Metrópoles", group: "br-jornais", section: "brasil", blurb: "Portal de Brasília. Política, cidades e o noticiário que sai da capital." },
  { handle: "VEJA", name: "Veja", group: "br-jornais", section: "brasil", blurb: "Revista semanal. Política nacional e o recorte clássico das bancas." },

  { handle: "Poder360", name: "Poder360", group: "br-politica", section: "brasil", blurb: "Jornal digital de Brasília. Política e poder, sem caderno de celebridade." },
  { handle: "congressoemfoco", name: "Congresso em Foco", group: "br-politica", section: "brasil", blurb: "Cobertura do Congresso. Votações, bastidor e o que anda no Anexo." },
  { handle: "TheInterceptBr", name: "The Intercept Brasil", group: "br-politica", section: "brasil", blurb: "Jornalismo investigativo. Poder, justiça e os documentos que vazam." },
  { handle: "cartacapital", name: "CartaCapital", group: "br-politica", section: "brasil", blurb: "Revista de política e cultura. Análise de Brasília e do debate público." },
  { handle: "agencialupa", name: "Agência Lupa", group: "br-politica", section: "brasil", blurb: "Agência de checagem. Desmente o que circula na política brasileira." },
  { handle: "AndreiaSadi", name: "Andréia Sadi", group: "br-politica", section: "brasil", blurb: "GloboNews. Bastidor de Brasília e a cobertura diária do Planalto." },
  { handle: "gcamarotti", name: "Gerson Camarotti", group: "br-politica", section: "brasil", blurb: "GloboNews. Correspondente político e o termômetro do Congresso." },
  { handle: "NatuzaNery", name: "Natuza Nery", group: "br-politica", section: "brasil", blurb: "GloboNews. Política nacional e o que o governo negocia em silêncio." },

  { handle: "valoreconomico", name: "Valor Econômico", group: "br-economia", section: "brasil", blurb: "Jornal de economia e finanças. Mercado, empresas e Brasília." },
  { handle: "exame", name: "Exame", group: "br-economia", section: "brasil", blurb: "Negócios, economia e carreiras no Brasil." },
  { handle: "infomoney", name: "InfoMoney", group: "br-economia", section: "brasil", blurb: "Portal de mercado. Ações, juros e o que o investidor lê de manhã." },
  { handle: "BrazilJournal", name: "Brazil Journal", group: "br-economia", section: "brasil", blurb: "Negócios e finanças. Empresas, M&A e o recorte executivo." },
  { handle: "BloombergLinea", name: "Bloomberg Línea", group: "br-economia", section: "brasil", blurb: "Bloomberg na América Latina. Mercado, empresas e a leitura regional." },
  { handle: "neofeed", name: "NeoFeed", group: "br-economia", section: "brasil", blurb: "Negócios e inovação. Empresas brasileiras e o que o mercado discute." },

  { handle: "reinaldoazevedo", name: "Reinaldo Azevedo", group: "br-colunistas", section: "brasil", blurb: "Colunista e comentarista. BandNews, Metrópoles e opinião política diária." },
  { handle: "brumelianebrum", name: "Eliane Brum", group: "br-colunistas", section: "brasil", blurb: "Escritora e jornalista. Sumaúma, Amazônia e o Brasil fora do eixo." },
  { handle: "guilherme_amado", name: "Guilherme Amado", group: "br-colunistas", section: "brasil", blurb: "Jornalista. Coluna e bastidor político com nome próprio." },
  { handle: "miriamleitao", name: "Miriam Leitão", group: "br-colunistas", section: "brasil", blurb: "Colunista de economia do Globo. Juros, fiscal e o recorte que pauta o dia." },
  { handle: "thaisheredia", name: "Thais Herédia", group: "br-colunistas", section: "brasil", blurb: "Comentarista de economia. CNN e a tradução do Copom para o público." },
  { handle: "monicabergamo", name: "Mônica Bergamo", group: "br-colunistas", section: "brasil", blurb: "Colunista da Folha. Bastidor de São Paulo, política e cultura." },
  { handle: "BlogdoNoblat", name: "Ricardo Noblat", group: "br-colunistas", section: "brasil", blurb: "Colunista político. O blog que ainda marca o noticiário de Brasília." },
  { handle: "JosiasdeSouza", name: "Josias de Souza", group: "br-colunistas", section: "brasil", blurb: "Comentarista do UOL. Bastidor político depois de décadas na Folha." },
  { handle: "BernardoMF", name: "Bernardo Mello Franco", group: "br-colunistas", section: "brasil", blurb: "Colunista do Globo. Política nacional com assinatura própria." },

  { handle: "STF_oficial", name: "STF", group: "br-instituicoes", section: "brasil", blurb: "Supremo Tribunal Federal. Pauta, sessões e os comunicados da Corte." },
  { handle: "TSEjusbr", name: "TSE", group: "br-instituicoes", section: "brasil", blurb: "Tribunal Superior Eleitoral. Conta oficial citada pelo próprio TSE." },
  { handle: "MinFazenda", name: "Ministério da Fazenda", group: "br-instituicoes", section: "brasil", blurb: "Conta oficial da Fazenda. Política econômica e os números do Tesouro." },
  { handle: "BancoCentralBR", name: "Banco Central", group: "br-instituicoes", section: "brasil", blurb: "Banco Central do Brasil. Copom, câmbio e os comunicados de política monetária." },
  { handle: "ibgeoficial", name: "IBGE", group: "br-instituicoes", section: "brasil", blurb: "IBGE. Inflação, desemprego, PIB e os dados que o país usa." },
  { handle: "SenadoFederal", name: "Senado Federal", group: "br-instituicoes", section: "brasil", blurb: "Conta oficial do Senado. Sessões, projetos e a pauta da Casa." },
  { handle: "CamaraDeputados", name: "Câmara dos Deputados", group: "br-instituicoes", section: "brasil", blurb: "Conta oficial da Câmara. Votações, comissões e o plenário." },
  { handle: "TCUoficial", name: "TCU", group: "br-instituicoes", section: "brasil", blurb: "Tribunal de Contas da União. Contas públicas e o controle do gasto." },
];
