export const RSS_ACCOUNT_RE: RegExp;
export const YOUTUBE_ACCOUNT_RE: RegExp;
export const YOUTUBE_POST_RE: RegExp;
export function sha256Hex(value: string): string;
export function rssAccountId(feedUrl: string): string;
export function youtubeAccountId(channelIdOrFeedUrl: string): string;
export function rssPostId(guidOrLink: string): string;
export function youtubePostId(videoId: string): string;
export function isRssAccount(handle: string): boolean;
export function isYouTubeAccount(handle: string): boolean;
export function isYouTubePostId(id: string): boolean;
