/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as SalvosRouteImport } from './routes/salvos'
import { Route as ApiCacheRouteImport } from './routes/api/cache'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiWatchRouteImport } from './routes/api/watch'
import { Route as MateriaIdRouteImport } from './routes/materia.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvosRoute = SalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheRoute = ApiCacheRouteImport.update({
  id: '/api/cache',
  path: '/api/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchRoute = ApiWatchRouteImport.update({
  id: '/api/watch',
  path: '/api/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaIdRoute = MateriaIdRouteImport.update({
  id: '/materia/$id',
  path: '/materia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/referencias': typeof ReferenciasRoute
  '/salvos': typeof SalvosRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/watch': typeof ApiWatchRoute
  '/materia/$id': typeof MateriaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/referencias': typeof ReferenciasRoute
  '/salvos': typeof SalvosRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/watch': typeof ApiWatchRoute
  '/materia/$id': typeof MateriaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes': typeof FontesRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/referencias': typeof ReferenciasRoute
  '/salvos': typeof SalvosRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/watch': typeof ApiWatchRoute
  '/materia/$id': typeof MateriaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/configuracoes'
    | '/fontes'
    | '/instalar'
    | '/login'
    | '/referencias'
    | '/salvos'
    | '/api/cache'
    | '/api/feed'
    | '/api/health'
    | '/api/ingest'
    | '/api/profile'
    | '/api/push'
    | '/api/watch'
    | '/materia/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/configuracoes'
    | '/fontes'
    | '/instalar'
    | '/login'
    | '/referencias'
    | '/salvos'
    | '/api/cache'
    | '/api/feed'
    | '/api/health'
    | '/api/ingest'
    | '/api/profile'
    | '/api/push'
    | '/api/watch'
    | '/materia/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/configuracoes'
    | '/fontes'
    | '/instalar'
    | '/login'
    | '/referencias'
    | '/salvos'
    | '/api/cache'
    | '/api/feed'
    | '/api/health'
    | '/api/ingest'
    | '/api/profile'
    | '/api/push'
    | '/api/watch'
    | '/materia/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FontesRoute: typeof FontesRoute
  InstalarRoute: typeof InstalarRoute
  LoginRoute: typeof LoginRoute
  ReferenciasRoute: typeof ReferenciasRoute
  SalvosRoute: typeof SalvosRoute
  ApiCacheRoute: typeof ApiCacheRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiWatchRoute: typeof ApiWatchRoute
  MateriaIdRoute: typeof MateriaIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvos': {
      id: '/salvos'
      path: '/salvos'
      fullPath: '/salvos'
      preLoaderRoute: typeof SalvosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache': {
      id: '/api/cache'
      path: '/api/cache'
      fullPath: '/api/cache'
      preLoaderRoute: typeof ApiCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch': {
      id: '/api/watch'
      path: '/api/watch'
      fullPath: '/api/watch'
      preLoaderRoute: typeof ApiWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$id': {
      id: '/materia/$id'
      path: '/materia/$id'
      fullPath: '/materia/$id'
      preLoaderRoute: typeof MateriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FontesRoute: FontesRoute,
  InstalarRoute: InstalarRoute,
  LoginRoute: LoginRoute,
  ReferenciasRoute: ReferenciasRoute,
  SalvosRoute: SalvosRoute,
  ApiCacheRoute: ApiCacheRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiPushRoute: ApiPushRoute,
  ApiWatchRoute: ApiWatchRoute,
  MateriaIdRoute: MateriaIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
